spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        javax:
          cache:
            provider: org.apache.ignite.cache.CachingProvider
        cache:
          use_second_level_cache: true
          use_query_cache: true
          generate_statistics: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
      org:
        apache:
          ignite:
            hibernate:
              ignite_instance_name: test-soumen
              default_access_type: READ_WRITE
app:
  ignite:
    address: localhost:10800
    instance_name: test_soumen