spring:
  datasource:
    url: jdbc:postgresql://10.95.31.66:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          generate_statistics: true
          region:
            factory_class: org.apache.ignite.cache.hibernate.HibernateRegionFactory
      org:
        apache:
          ignite:
            hibernate:
              ignite_instance_name: test-soumen
              default_access_type: READ_WRITE
app:
  ignite:
    address: 10.95.31.66:47500
    instance_name: test_soumen